namespace HyperCasualTemplate
{
    public static class Enums
    {
        /// <summary>
        /// タッチイベントの種別
        /// </summary>
        public enum TouchInfo
        {
            None = 99,
            Began = 0,
            Moved = 1,
            Stationary = 2,
            Ended = 3,
            Canceled = 4,
        }

        public enum ColorString
        {
            yellow,
            green,
            red
        }


        public enum InAppStatus
        {
            NotAvailable,
            Owned,
            NotOwned
        }

        public enum ActionClick
        {
            None = 0,
            Play = 1,
            Rate = 2,
            Share = 3,
            Policy = 4,
            Feedback = 5,
            Term = 6,
            Energy = 7,
            Coin = 8,
            Gem = 9,
            NoAds = 10,
            Settings = 11,
            Quest = 12,
            DailyQuest = 13
        }

        public enum Reason
        {
            DailyReward = 0,
            InApp = 1,
            Ads = 2,
            QuestReward = 3,
            DailyQuestReward = 4,
            DailyLogin = 5
        }

        public enum TypeItem
        {
            Coin = 0,
            Gem = 1,
            Energy = 2,
            RemoveADS = 3
        }

        public enum TypePackIAP
        {
            GEM_1 = 0,
            GEM_2 = 1,
            GEM_3 = 3,
            GEM_4 = 4,
            ROMOVE_ADS = 5,
        }

        public enum ActionWatchVideo
        {
            Replay = 0,
            AddGem_InShop = 1,
            X2Coin_EndGame = 2,
            Quest_WacthVideo = 3,
            Upgrade_Player = 4,
            AddCoin_InUpgradePlayer = 5,
            BuyShop = 6,
            DailyLogin = 7,
            Popup_Show_Ads = 8,
            VideoGirl = 9,
            BuyItemPlayer = 10,
            BuyItemPlayerRandom = 11,
            X2VQMM = 12,
            OnlineReward = 13,
            SpinADS = 14,
            RewardAccumulate = 15,
            RewardAccumulateX2 = 16,
            BuyItemEndless = 17,
        }

        public enum QuestEnum
        {
            Kill_X_Enemy = 0,
            Complete_X_Level = 1,
            Watch_X_Video = 2,
            Finish_With_Full_Health = 3,
            Pass_Level_With_No_Damage = 4,
            Spent_X_Gem = 5,
            Unlock_New_X_Character = 6
        }

        public enum TypeChest
        {
            Common = 0,
            Rare = 1,
            Epic = 2
        }

        public enum QuestStatus
        {
            Doing = 0,
            Finished = 1,
            Claimed = 2
        }
    }
    
    public enum CountryCode
        {
            AF,
            AX,
            AL,
            DZ,
            AS,
            AD,
            AO,
            AI,
            AQ,
            AG,
            AR,
            AM,
            AW,
            AU,
            AT,
            AZ,
            BS,
            BH,
            BD,
            BB,
            BY,
            BE,
            BZ,
            BJ,
            BM,
            BT,
            BO,
            BQ,
            BA,
            BW,
            BV,
            BR,
            IO,
            BN,
            BG,
            BF,
            BI,
            KH,
            CM,
            CA,
            CV,
            KY,
            CF,
            TD,
            CL,
            CN,
            CX,
            CC,
            CO,
            KM,
            CG,
            CD,
            CK,
            CR,
            CI,
            HR,
            CU,
            CW,
            CY,
            CZ,
            DK,
            DJ,
            DM,
            DO,
            EC,
            EG,
            SV,
            GQ,
            ER,
            EE,
            ET,
            FK,
            FO,
            FJ,
            FI,
            FR,
            GF,
            PF,
            TF,
            GA,
            GM,
            GE,
            DE,
            GH,
            GI,
            GR,
            GL,
            GD,
            GP,
            GU,
            GT,
            GG,
            GN,
            GW,
            GY,
            HT,
            HM,
            VA,
            HN,
            HK,
            HU,
            IS,
            IN,
            ID,
            IR,
            IQ,
            IE,
            IM,
            IL,
            IT,
            JM,
            JP,
            JE,
            JO,
            KZ,
            KE,
            KI,
            KP,
            KR,
            KW,
            KG,
            LA,
            LV,
            LB,
            LS,
            LR,
            LY,
            LI,
            LT,
            LU,
            MO,
            MK,
            MG,
            MW,
            MY,
            MV,
            ML,
            MT,
            MH,
            MQ,
            MR,
            MU,
            YT,
            MX,
            FM,
            MD,
            MC,
            MN,
            ME,
            MS,
            MA,
            MZ,
            MM,
            NA,
            NR,
            NP,
            NL,
            NC,
            NZ,
            NI,
            NE,
            NG,
            NU,
            NF,
            MP,
            NO,
            OM,
            PK,
            PW,
            PS,
            PA,
            PG,
            PY,
            PE,
            PH,
            PN,
            PL,
            PT,
            PR,
            QA,
            RE,
            RO,
            RU,
            RW,
            BL,
            SH,
            KN,
            LC,
            MF,
            PM,
            VC,
            WS,
            SM,
            ST,
            SA,
            SN,
            RS,
            SC,
            SL,
            SG,
            SX,
            SK,
            SI,
            SB,
            SO,
            ZA,
            GS,
            SS,
            ES,
            LK,
            SD,
            SR,
            SJ,
            SZ,
            SE,
            CH,
            SY,
            TW,
            TJ,
            TZ,
            TH,
            TL,
            TG,
            TK,
            TO,
            TT,
            TN,
            TR,
            TM,
            TC,
            TV,
            UG,
            UA,
            AE,
            GB,
            US,
            UM,
            UY,
            UZ,
            VU,
            VE,
            VN,
            VG,
            VI,
            WF,
            EH,
            YE,
            ZM,
            ZW,
            NONE
        }

    public enum GameState
    {
        NORMAL,
        PLAYING
    }
}